# Generated by Django 5.2.9 on 2025-12-16 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=45)),
                ('site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('valor_pag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pag', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('conta_bancaria', models.CharField(max_length=45)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorSorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('valor_parc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pag', models.DateField()),
                ('data_venc', models.DateField()),
                ('status_pag', models.CharField(max_length=45)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Sorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('tipo_prod', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('fabricacao', models.DateField(blank=True, null=True)),
                ('fornecedores', models.ManyToManyField(through='app.FornecedorSorvete', to='app.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='MovEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_estq', models.IntegerField()),
                ('data_estoq', models.DateField()),
                ('motivo', models.CharField(max_length=45)),
                ('tipo_mov', models.CharField(max_length=45)),
                ('sorvete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorvete')),
            ],
        ),
        migrations.AddField(
            model_name='fornecedorsorvete',
            name='sorvete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorvete'),
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pag', models.CharField(max_length=45)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.CharField(max_length=45)),
                ('desconto_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendas'),
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sorvete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorvete')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=8)),
                ('tipo_usuario', models.IntegerField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='SaborSorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sabor')),
                ('sorvete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorvete')),
            ],
            options={
                'unique_together': {('sabor', 'sorvete')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fornecedorsorvete',
            unique_together={('fornecedor', 'sorvete')},
        ),
    ]
